/**
 * VoiceoverPromo — Website promo with Resemble AI voiceover + synced animations.
 *
 * Before using this composition:
 *   1. Run: npm run voiceover promo
 *   2. Check public/audio/promo.json for durationFrames
 *   3. Update the <Composition durationInFrames> in Root.tsx to match
 */

import React from 'react';
import {
  AbsoluteFill,
  Audio,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
  spring,
  interpolate,
  Sequence,
} from 'remotion';
import { GradientBg } from '../components/GradientBg';
import { NoiseBg } from '../components/NoiseBg';
import { KineticText } from '../components/KineticText';
import { BlurReveal } from '../components/BlurReveal';
import { PALETTE, SPRING } from '../style/tokens';
import type { WordTimestamp } from '../lib/voiceover';

// Word timestamps are loaded at runtime from a sidecar JSON file.
// Run `npm run voiceover` to generate it.
// Until then, animations run without audio sync (empty array = no highlights).
const timestamps: WordTimestamp[] = (() => {
  if (typeof window !== 'undefined') return []; // skip in browser context
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const fs = require('fs') as typeof import('fs');
    const p = require('path') as typeof import('path');
    const jsonPath = p.join(process.cwd(), 'public', 'audio', 'promo.json');
    if (fs.existsSync(jsonPath)) {
      return JSON.parse(fs.readFileSync(jsonPath, 'utf8')).wordTimestamps ?? [];
    }
  } catch {
    // file not generated yet
  }
  return [];
})();

interface VoiceoverPromoProps {
  headline?: string;
  subheadline?: string;
  cta?: string;
  brandName?: string;
  palette?: keyof typeof PALETTE;
  hasAudio?: boolean;
}

/**
 * Get the active word at the current frame based on Resemble timestamps.
 */
function useActiveWord(frame: number, fps: number): string | null {
  const currentSec = frame / fps;
  const active = timestamps.find(
    (w) => currentSec >= w.start && currentSec <= w.end
  );
  return active?.word ?? null;
}

export const VoiceoverPromo: React.FC<VoiceoverPromoProps> = ({
  headline = 'Build faster.',
  subheadline = 'Ship production-ready websites in minutes with AI. No design skills needed.',
  cta = 'Start Free →',
  brandName = 'UIGen',
  palette = 'obsidian',
  hasAudio = true,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const p = PALETTE[palette];
  const activeWord = useActiveWord(frame, fps);

  // CTA spring entrance
  const ctaProgress = spring({ frame: frame - 50, fps, config: SPRING.BOUNCY });
  const ctaScale = interpolate(ctaProgress, [0, 1], [0.85, 1]);
  const ctaOpacity = interpolate(ctaProgress, [0, 0.4], [0, 1], { extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill
      style={{
        background: p.bg,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'column',
        padding: '0 160px',
        textAlign: 'left',
      }}
    >
      {/* Background layers */}
      <GradientBg colors={[p.bg, p.surface, p.surface]} speed={0.08} />
      <NoiseBg opacity={0.03} />

      {/* Voiceover audio — generated by scripts/generate-voiceover.ts */}
      {hasAudio && (
        <Audio src={staticFile('audio/promo.wav')} />
      )}

      {/* Brand */}
      <BlurReveal from={0} direction="down">
        <div
          style={{
            fontSize: 16,
            color: p.accent,
            letterSpacing: '0.22em',
            textTransform: 'uppercase',
            fontFamily: 'monospace',
            marginBottom: 48,
          }}
        >
          {brandName}
        </div>
      </BlurReveal>

      {/* Headline */}
      <KineticText
        text={headline}
        from={8}
        mode="slideUp"
        fontSize={128}
        color={p.text}
        staggerFrames={8}
      />

      {/* Subheadline — word-by-word highlight synced to voiceover */}
      <BlurReveal from={20} direction="up">
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: '0.3em',
            marginTop: 28,
            fontSize: 26,
            fontFamily: '"DM Sans", sans-serif',
            fontWeight: 400,
            lineHeight: 1.55,
            maxWidth: 760,
          }}
        >
          {subheadline.split(' ').map((word, i) => {
            const isActive = activeWord?.toLowerCase() === word.toLowerCase().replace(/[^a-z]/g, '');
            return (
              <span
                key={i}
                style={{
                  color: isActive ? p.accent : p.muted,
                  transition: 'color 80ms',
                  fontWeight: isActive ? 600 : 400,
                }}
              >
                {word}
              </span>
            );
          })}
        </div>
      </BlurReveal>

      {/* CTA button */}
      <div
        style={{
          marginTop: 56,
          opacity: ctaOpacity,
          transform: `scale(${ctaScale})`,
          background: p.accent,
          color: p.bg,
          fontSize: 22,
          fontWeight: 700,
          padding: '18px 52px',
          borderRadius: 8,
          letterSpacing: '0.05em',
          fontFamily: '"Space Grotesk", sans-serif',
          alignSelf: 'flex-start',
          boxShadow: `0 0 60px ${p.accent}40`,
        }}
      >
        {cta}
      </div>

      {/* Word indicator (debug — remove in production) */}
      {process.env.NODE_ENV === 'development' && activeWord && (
        <div
          style={{
            position: 'absolute',
            bottom: 32,
            right: 48,
            fontSize: 14,
            color: `${p.muted}80`,
            fontFamily: 'monospace',
          }}
        >
          ▶ {activeWord}
        </div>
      )}
    </AbsoluteFill>
  );
};
